---
- name: Automating Windows with Red Hat Ansible
  hosts: all
  gather_facts: false
  tasks:
   - name: Usuario ansible con privilegios de administrador
     win_user:
       name: ansible
       password: "Redhat1!"
       state: present
       groups:
           - Administrators
     register: user
   - debug: var=user  
            
   - name: Instalación de Telnet-Client
     win_feature:
       name: "Telnet-Client"
       state: present
       restart: False
       include_sub_features: True
       include_management_tools: True
     register: telnet
   - debug: var=telnet
    
   - name: Instalación de IIS Web-Server con management tools
     win_feature:
       name: Web-Server
       state: present
       include_sub_features: yes
       include_management_tools: yes
       register: win_feature 
   - debug: var=iss
   
   - name: Colocar el archivo neerdd.jpg en la ruta c:\Users\Administrator\Downloads
     win_copy:
        src: files/neerdd.jpg
        dest: c:\Users\Administrator\Downloads\neerdd.jpg
   - debug: var=copy
    
   - name: Ejecutar el PowerShell script helloworld.ps1
     script: files/helloworld.ps1
     register: script
   - debug: var=script
     
   - name: Obtener dirección IP del equipo
     raw: ipconfig
     register: ipconfig
   - debug: var=ipconfig
   
   - name: Validar el estatus del win.ini
     win_stat: path="C:/Windows/win.ini"
     register: stat_file 
   - debug: var=stat_file
    
   - name: check stat_file result
     assert:
          that:
             - "stat_file.stat.exists"
             - "not stat_file.stat.isdir"
             - "stat_file.stat.size > 0"
